<?php
$title = 'role';
$this->headTitle($title);
?>

<h2><?php echo $this->escapeHtml($title); ?></h2>

<?php if ($this->isAllowed('role', 'add')): ?>
<p>
    <a href="<?php echo $this->url('role', array('action'=>'add'));?>">Přidat novou roli</a>
</p>
<?php endif; ?>

<table class="table">
<tr>
    <th>Název</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($roles as $role) : ?>

<tr>
    <td><?php echo $this->escapeHtml($role->name);?></td>
    <td>
        <?php if ($this->isAllowed('role', 'edit')): ?>
        <a href="<?php echo $this->url('role', array('action'=>'edit', 'id' => $role->id_role));?>">Upravit</a>
        <?php endif; ?>
        <?php if ($this->isAllowed('role', 'rights')): ?>
        <a href="<?php echo $this->url('role', array('action'=>'rights', 'id' => $role->id_role));?>">Oprávnění</a>
        <?php endif; ?>
        <?php if ($this->isAllowed('role', 'delete') && $role->id_role != \System\Service\RoleManager::ID_ROLE_GUEST): ?>
        <a href="<?php echo $this->url('role', array('action'=>'delete', 'id' => $role->id_role));?>">Smazat</a>
        <?php endif; ?>
    </td>
</tr>
<?php endforeach; ?>
</table>