<?php

$title = 'upravit uživatele';
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'user',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id_user'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('surname'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('password2'));
echo $this->formRow($form->get('id_role'));
echo $this->formRow($form->get('is_admin'));
echo '<div class="form_controls">';
echo $this->formSubmit($form->get('submit'));
echo $this->formSubmit($form->get('return'));
echo '</div>';
echo $this->form()->closeTag();