<?php
$title = 'uživatelé';
$this->headTitle($title);
?>

<h2><?php echo $this->escapeHtml($title); ?></h2>

<?php if ($this->isAllowed('user', 'add')): ?>
<p>
    <a href="<?php echo $this->url('user', array('action'=>'add'));?>">
        Přidat nového uživatele
    </a>
</p>
<?php endif; ?>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'index')));
$form->prepare();


echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>

<table class="table">
<tr>
    <th>Jméno</th>
    <th>Příjmení</th>
    <th>Email</th>
    <th>Poslední přihlášení</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($users as $user) : ?>

<tr>
    <td><?php echo $this->escapeHtml($user->name);?></td>
    <td><?php echo $this->escapeHtml($user->surname);?></td>
    <td><?php echo $this->escapeHtml($user->email);?></td>
    <td><?php echo \is_object($user->last_login)? $this->escapeHtml($user->last_login->format('d.m.Y H:i:s')) : null ?></td>
    <td>
        <?php if ($this->isAllowed('user', 'edit')): ?>
            <a href="<?php echo $this->url('user', array(
                'action'=>'edit', 
                'id' => $user->id_user,
                'page' => $users->getCurrentPageNumber())) . '?' .  http_build_query($this->requestParams);?>"
                >Upravit</a>
        <?php endif; ?>
        <?php if ($this->isAllowed('user', 'role')): ?>
            <a href="<?php echo $this->url('user', array(
                'action'=>'role', 
                'id' => $user->id_user,
                'page' => $users->getCurrentPageNumber())) . '?' .  http_build_query($this->requestParams);?>"
                >Role</a>
        <?php endif; ?>
        <?php if ($this->isAllowed('user', 'delete')): ?>
            <a href="<?php echo $this->url('user', array(
                'action'=>'delete', 
                'id' => $user->id_user,
                'page' => $users->getCurrentPageNumber())) . '?' .  http_build_query($this->requestParams);?>"
                >Smazat</a>
        <?php endif; ?>
    </td>
</tr>
<?php endforeach; ?>
</table>

<?php
echo $this->paginationControl($users, 'Sliding', 'system/system_pagination_control', array('route' => 'user', 'action' => 'index', 'requestParams' => $requestParams));
?>