<?php

$title = 'členství ve skupinách';
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'user',
    array(
        'action' => 'role',
        'id'     => $this->id,
        'page' => $page
    )
) . '?' .  http_build_query($this->requestParams));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formCollection($form);

echo $this->form()->closeTag();

