<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('403 - neoprávněný přístup') ?>
        <style>
          body {
            background-color: #e0e0e0;
            text-align: center;
            padding-top: 50px;
          }
          h1 {
            border: 3px solid #b02e2e;
            padding: 15px;
            display: inline;
          }
        </style>
    </head>

    <body>
      <h1>403 - neoprávněný přístup</h1>
    </body>
</html>
